### PR TITLE
MAINT: make the "BLAS / LAPACK on Windows" page visible in TocTree

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
note: 2 last commits on top of the alabaster support - may need a rebase.

**Comment by techtonik** [comment]
Can you paste a screen how it looks like here? Alt-PrtScr + Ctrl-Ins.

**Comment by rgommers** [comment]
Sure:

blaslapack

**Comment by techtonik** [comment]
Is it main content or a side nav? Also, the nav on index.html is different from other pages.

**Comment by carlkl** [comment]
sucessfully tested with sphinx-1.2.0 and 1.3.1

**Comment by rgommers** [comment]
> Is it main content or a side nav? Also, the nav on index.html is different from other pages.

Main content, compare with main page now.

**Pull request merged**
