### PR TITLE
More technical details and a bit more motivation

### PR DESCRIPTION
**Pull request by njsmith**

### CODE REVIEW

**Comment by matthew-brett** [comment]
Looks good.   Do you think it's time to split the MSVS 2015 material out into a new page?

@carlkl - any thoughts about the `vcruntime` stuff?

**Comment by njsmith** [comment]
Eh, could be split off, sure. I just wanted to get this down somewhere
durable while I was thinking about it :-)

On Fri, Dec 18, 2015 at 12:58 AM, Matthew Brett notifications@github.com
wrote:

> Looks good. Do you think it's time to split the MSVS 2015 material out
> into a new page?
> 
> @carlkl https://github.com/carlkl - any thoughts about the vcruntime
> stuff?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mingwpy/mingwpy.github.io/pull/2#issuecomment-165717572
> .

## 

Nathaniel J. Smith -- http://vorpus.org

**Comment by matthew-brett** [comment]
Do you want me to merge and then propose a split?

**Comment by njsmith** [comment]
That would be great, thanks!

**Comment by matthew-brett** [comment]
Carl - any comments here?

**Comment by carlkl** [comment]
I will merge this for reference. I cannot give qualified answers straight away. 
It may be possible to link against msvcrt instead of vcruntime140 for some of the functions, as there is no heap allocation (this has to be carefully checked). Using straightforward written code for string functions might not a good idea, see ie `"A Study in Memcmp"` http://www.picklingtools.com/study.pdf

**Comment by carlkl** [comment]
Regarding setjump/longjump see this threads:
http://www.mail-archive.com/mingw-w64-public%40lists.sourceforge.net/msg11829.html
https://stat.ethz.ch/pipermail/r-sig-windows/2015q3/000015.html

**Comment by njsmith** [comment]
Fwiw those setjmp/longjmp problems appear to be when trying to use the
implementation in msvcrt.

**Comment by njsmith** [comment]
And I am not worried about memcmp / memcpy performance at this stage. They
are certainly important, but the rule is: first make it correct, then make
it fast. (And modern gcc with auto-vectorization may well compile even a
naive loop into something more respectable than the gcc that was used in
that paper.)

**Comment by carlkl** [comment]
maybe mingww64 ironcrate branch could be used as a template
http://sourceforge.net/p/mingw-w64/code-ironcrate/ci/master/tree/memory

**Comment by matthew-brett** [comment]
What is the 'ironcrate' branch?

**Comment by njsmith** [comment]
I'm wondering the same thing :-). (I wish mingw-w64 didn't use this
terrible source forge stuff; it makes it impossible to find information on
things :-()

**Pull request merged**
