### PR TITLE
Add mingwpy page from numpy.wiki

### PR DESCRIPTION
**Pull request by matthew-brett**
Refactor Mingw-static-toolchain page from numpy wiki, by moving issues
into the `issues` page, and a little rearranging.

### CODE REVIEW

**Comment by carlkl** [comment]
I propose to mention mingw-static-toolchain only as reference in the history of mingwpy.
The recent mingwpy toolchain is https://anaconda.org/carlkl/mingwpy and can be installed with pip. The necessary import libraries for python and the msvcr runtime are included in the wheel archive.

**Comment by matthew-brett** [comment]
I don't know the details of how the package contents has changed, but I did my best.  How does it look now?

**Comment by carlkl** [comment]
I will merge now and correct the text later on

**Comment by matthew-brett** [comment]
Great - thanks.

**Pull request merged**
