### PR TITLE
BLD: support older Sphinx versions than 1.3 - those don't include alabaster

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
Oh, and: I really don't want to upgrade Sphinx, because Sphinx 1.3 is horribly broken (Scipy docs don't build with it).

**Comment by carlkl** [comment]
html and latex tested with sphinx=1.2.0 and  1.3.1 - looks good

**Comment by techtonik** [comment]
@rgommers add `alabaster` to requirements.

**Comment by techtonik** [comment]
Sphinx includes it as a dependency too - https://github.com/sphinx-doc/sphinx/blob/master/setup.py#L55

**Comment by rgommers** [comment]
@techtonik OK thanks, will send a follow-up PR

**Comment by rgommers** [comment]
done in gh-14

**Pull request merged**
