### PR TITLE
DOC: add a Roadmap and the proposal submitted to NumFOCUS/PSF (Dec'15)

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by carlkl** [comment]
great addition!

**Comment by rgommers** [comment]
@matthew-brett my repo rights are still in progress, so if you could `make github` this that would be great.

**Comment by rgommers** [comment]
and thanks for merging Carl

**Comment by matthew-brett** [comment]
I built the docs and pushed them.

**Comment by rgommers** [comment]
thanks!

**Comment by matthew-brett** [comment]
Carl - OK for me to add Ralf as an org owner?

**Comment by rgommers** [comment]
> Carl - OK for me to add Ralf as an org owner?

Carl did add me as team maintainer yesterday, which is perfectly fine. The one remaining issue is that this repo is configured as read-only here: https://github.com/orgs/mingwpy/teams/core/repositories

**Comment by ogrisel** [comment]
It shows up as "admin" to me. Has this been fixed already?

**Comment by carlkl** [comment]
@ogrisel , is the setup ok for you?

**Comment by ogrisel** [comment]
Yes.

**Comment by rgommers** [comment]
yep, fixed now - thanks!

**Pull request merged**
