### PR TITLE
NF: add BLAS / LAPACK page

### PR DESCRIPTION
**Pull request by matthew-brett**

### CODE REVIEW

**Comment by rgommers** [comment]
very nice indeed

**Comment by rgommers** [comment]
I would suggest making this page more discoverable. I thought at first that the website wasn't updated, but then found that http://mingwpy.github.io/blas_lapack.html is simply not in the ToC but only linked to from near the bottom of http://mingwpy.github.io/issues.html

**Comment by techtonik** [comment]
It is easy to add this to the root level of ToC, but I tried to see if it is possible to add this as "Issues" subsection. Quick scan of http://sphinx-doc.org/markup/toctree.html doesn't reveal anything and experiments need some time.

**Comment by rgommers** [comment]
@techtonik thanks for looking into that. I've proposed a way to get the TocTree to look right in gh-12.

**Pull request merged**
