### PR TITLE
Add security into motivations

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by carlkl** [comment]
There is a controversial debate about this topic. A fully agree on it, but this shouldn't be phrased as an officially requirement. Or is there a reference for that I'm not aware of?

**Comment by techtonik** [comment]
I am not sure how to rephrase that. These requirements are usually not published by media, so it is hard to find exact reference. There is an article about Chinese choice of operating system https://en.wikipedia.org/wiki/Kylin_(operating_system) that talks about "impenetratable" servers, and, well, I don't know a way to make a software impenetratable (or check it) without source code access.

**Comment by carlkl** [comment]
I propose to leave the text as it is and close the PR. It is of course desirable to use open source, but there is no security requirement or security commitment for mingwpy beyond the BSD license and all the other licenses included at all.

**Comment by njsmith** [comment]
Yeah, this would be OK if there was something we could cite showing that these security certifications that require open source were (a) real, (b) being applied to scientific python code, (c) running in Windows (an odd choice if you're paranoid enough to worry about backdoors in proprietary software from large corporations). Without that it might be true but still comes across as grasping at straws I think, which is unnecessary since we have plenty of stronger motivations.

**Comment by techtonik** [comment]
Citation is an argument. Right now I can't find any, so I'll keep looking. But security considerations make `mingwpy` an appropriate candidate for applying to https://www.opentech.fund/ grants.

**Comment by njsmith** [comment]
Huh, didn't know about them. I don't think mingwpy is looking for additional funding right now, and if/when it is then there are other grant-giving bodies that might be more appropriate to try first, but who knows, it's always good to be aware of these options :-).

**Comment by techtonik** [comment]
I am looking for additional funding. For #18. =) Ok, let's close this for until there is a good source to cite.

**Pull request closed without merging**
